--- #---------------------数据库配置---------------------------
fablex:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: novel
    username: root
    password: 123456

--- #---------------------自定义配置----------------------------
fablex:
  port: 8081
  # JWT
  jwt:
    secret: E66559580A1ADF48CDD928516062F12F
    expire: 86400000
# 开启 SpringDoc 接口文档
springdoc:
  api-docs:
    enabled: true
--- #---------------------中间件配置---------------------------
fablex:
  # Redis 配置
  redis:
    host: 192.168.254.128
    port: 6379
    password: 123456
    database: 1
  # Spring AMQP 配置
  amqp:
    # 是否开启 Spring AMQP：true-开启 false-不开启
    enabled: true
    # RabbitMQ 配置
  rabbitmq:
    addresses: "amqp://guest:guest@192.168.254.128:5672"
    virtual-host: fablex

  # XXL-JOB 配置
  xxl:
    job:
      # 是否开启 XXL-JOB：true-开启 false-不开启
      enabled: true
      admin:
        ### 调度中心部署根地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
        addresses: http://127.0.0.1:8080/xxl-job-admin
      executor:
        ### 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
        appname: xxl-job-executor-fablex
        ### 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
        logpath: logs/xxl-job/jobhandler
      ### xxl-job, access token
      accessToken: 123456

--- #---------------------ES配置---------------------------
fablex:
  elasticsearch:
    enabled: true
    host: 127.0.0.1
    port: 9200
