#--------------------------通用配置-------------------------
spring:
  application:
    # 应用名
    name: fablex
  profiles:
    # 激活特定配置
    active: dev
--- #--------------------接口文档配置---------------------------
springdoc:
  api-docs:
    enabled: false
--- #---------------------数据库配置---------------------------
spring:
  datasource:
    url: jdbc:mysql://${fablex.datasource.host}:${fablex.datasource.port}/${fablex.datasource.database}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${fablex.datasource.username}
    password: ${fablex.datasource.password}
  # ShardingSphere-JDBC 配置
  # 配置是 ShardingSphere-JDBC 中唯一与应用开发者交互的模块，
  # 通过它可以快速清晰的理解 ShardingSphere-JDBC 所提供的功能。
#  shardingsphere:
#    # 是否开启分库分表
#    enabled: false
--- #----------------------Logbook配置-----------------------------
logbook:
  format:
    # 输出格式
    style: http
  obfuscate:
    headers:
      # 隐藏 Authorization 头信息
      - Authorization
    parameters:
      # 隐藏密码参数
      - password
--- #---------------------自定义配置----------------------------
fablex:
  # JWT
  jwt:
    secret: ${fablex.jwt.secret}
    expire: ${fablex.jwt.expire}
