#--------------------------通用配置-------------------------
spring:
  application:
    # 应用名
    name: fablex
  profiles:
    # 激活特定配置
    active: dev

server:
  port: ${fablex.port}
--- #--------------------接口文档配置---------------------------
springdoc:
  api-docs:
    enabled: false
--- #---------------------数据库配置---------------------------
spring:
  datasource:
    url: jdbc:mysql://${fablex.datasource.host}:${fablex.datasource.port}/${fablex.datasource.database}?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: ${fablex.datasource.username}
    password: ${fablex.datasource.password}
  # ShardingSphere-JDBC 配置
  # 配置是 ShardingSphere-JDBC 中唯一与应用开发者交互的模块，
  # 通过它可以快速清晰的理解 ShardingSphere-JDBC 所提供的功能。
#  shardingsphere:
#    # 是否开启分库分表
#    enabled: false
--- #----------------------Mybatis-plus配置-----------------------------
mybatis-plus:
#  类型别名
#  type-aliases-package: com.github.bhjj.dao
#  默认扫描类路径下的mapper包及其子包
  mapper-locations: "classpath*:/mapper/**/*.xml"
  configuration:
#    启用SQL日志打印到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    驼峰映射
    map-underscore-to-camel-case: true
#    二级缓存
    cache-enabled: false
  global-config:
    db-config:
#     默认由雪花算法生成主键(auto代表自增)
      id-type: assign_id
#      更新策略，只更新不为空的字段
      update-strategy: not_null

--- #----------------------Logbook配置-----------------------------
logbook:
  format:
    # 输出格式
    style: http
  obfuscate:
    headers:
      # 隐藏 Authorization 头信息
      - Authorization
    parameters:
      # 隐藏密码参数
      - password
--- #---------------------自定义配置----------------------------
fablex:
  # JWT
  jwt:
    secret: ${fablex.jwt.secret}
    expire: ${fablex.jwt.expire}

--- #---------------------中间件配置---------------------------
spring:
  data:
    # Redis 配置
    redis:
      host: ${fablex.redis.host}
      port: ${fablex.redis.port}
      password: ${fablex.redis.password}
      database: ${fablex.redis.database}
# XXL-JOB 配置
xxl:
  job:
    # 是否开启 XXL-JOB：true-开启 false-不开启
    enabled: true
    admin:
      ### 调度中心部署根地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      ### 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      appname: xxl-job-executor-fablex
      ### 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logpath: logs/xxl-job/jobhandler
    ### xxl-job, access token
    accessToken: 123456
--- #---------------------跨域配置---------------------------
# 项目配置
fablex:
  # 跨域配置
  cors:
    # 允许跨域的域名
    allow-origins:
      - http://localhost:1024
      - http://localhost:8081
--- #---------------------ES配置----------------------------
spring:
  elasticsearch:
    enabled: true
    host: ${fablex.elasticsearch.host}
    port: ${fablex.elasticsearch.port}